name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: architech_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Ensure all history is fetched for a clean checkout

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    # Python services linting and testing
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-asyncio pytest-cov

    - name: Lint Python code
      run: |
        flake8 services/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 services/ --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Test User Service
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/architech_test
        REDIS_URL: redis://localhost:6379/0
      run: |
        cd services/user-service
        python -m venv venv
        source venv/bin/activate
        echo "--- Diagnosing Python Environment ---"
        python --version
        pip --version
        pwd
        ls -l requirements.txt
        pip install httpx==0.27.0 # Explicitly install httpx with a specific version
        pip install pydantic-settings==2.2.1 --force-reinstall --no-cache-dir # Force install pydantic-settings
        pip install -r requirements.txt
        pip freeze
        echo "--- End Diagnosis ---"
        pytest tests/ -v --cov=app --cov-report=xml

    - name: Test Project Service
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/architech_test
        REDIS_URL: redis://localhost:6379/0
      run: |
        cd services/project-service
        python -m venv venv
        source venv/bin/activate
        pip install pydantic-settings==2.2.1 --force-reinstall --no-cache-dir # Force install pydantic-settings for other services
        pip install -r requirements.txt
        pytest tests/ -v --cov=app --cov-report=xml

    - name: Test Design Service
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/architech_test
        REDIS_URL: redis://localhost:6379/0
      run: |
        cd services/design-service
        python -m venv venv
        source venv/bin/activate
        pip install pydantic-settings==2.2.1 --force-reinstall --no-cache-dir # Force install pydantic-settings for other services
        pip install -r requirements.txt
        pytest tests/ -v --cov=app --cov-report=xml

    - name: Test Simulation Orchestration Service
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/architech_test
        REDIS_URL: redis://localhost:6379/0
      run: |
        cd services/simulation-orchestration-service
        python -m venv venv
        source venv/bin/activate
        pip install pydantic-settings==2.2.1 --force-reinstall --no-cache-dir # Force install pydantic-settings for other services
        pip install -r requirements.txt
        pytest tests/ -v --cov=app --cov-report=xml

    - name: Test API Gateway
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/architech_test
        REDIS_URL: redis://localhost:6379/0
      run: |
        cd services/api-gateway
        python -m venv venv
        source venv/bin/activate
        pip install pydantic-settings==2.2.1 --force-reinstall --no-cache-dir # Force install pydantic-settings for other services
        pip install -r requirements.txt
        pytest tests/ -v --cov=app --cov-report=xml

    # Frontend testing
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci

    - name: Lint frontend code
      run: |
        cd frontend
        npm run lint || true  # Don't fail on lint warnings initially

    - name: Test frontend
      run: |
        cd frontend
        npm test -- --coverage --watchAll=false

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    # Go simulation engine testing
    - name: Test Simulation Engine
      run: |
        cd simulation-engine
        go mod tidy
        go test -v ./...

  build-and-push:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service: [user-service, project-service, design-service, simulation-orchestration-service, api-gateway]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./services/${{ matrix.service }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  build-simulation-engine:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/simulation-engine
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./simulation-engine
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  build-frontend:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}


